app:
    resource: '@AppBundle/Controller/'
    type: annotation
<<<<<<< HEAD
=======

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
>>>>>>> f3042245b2ecc7db60cd1ab9dc423ff98ba62ea7
